name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    CI : false
        
jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    # dotnet build and publish
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build with dotnet
      run: dotnet build --configuration Release .\Project1
      
    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o dotnetcorewebapp .\Project1
        
    - name: Deploy to IIS
      run: |
        #iisreset /stop
        Copy-Item ./Project1/* C:/inetpub/wwwroot/Project1 -Recurse -Force
        #iisreset /start
    #- name: Curl the website as a smoke test
     # run: curl http://localhost/dotnetcore-webapp
    
